import os
import shutil
from setuptools import setup, Command

CWD = os.path.abspath(os.path.dirname(__file__))
BUILD_DIRS = [
    'auger.egg-info',
    'build',
    'dist',
]
INSTALL_DATA_FILES = [
    ('share/icons/hicolor/64x64/apps',
     ['data/org.m-flak.Auger.png']),
    ('share/applications',
     ['data/org.m-flak.Auger.desktop']),
]

def get_requirements():
    requirements = None
    req_txt = os.path.join(
        CWD,
        'requirements.txt'
    )

    with open(req_txt, 'r') as f:
        requirements = f.readlines()

    return list(map(
        lambda r: r.rstrip('\n'),
        requirements
    ))

class CleanCmd(Command):
    description = 'Remove all files & directories generated by build/bdist commands'
    user_options = []
    def initialize_options(self):
        pass
    def finalize_options(self):
        pass
    def run(self):
        clean_directories = list(map(
            lambda d: os.path.join(CWD, d),
            BUILD_DIRS
        ))

        for directory in clean_directories:
            if os.path.exists(directory):
                print('removing \'{}\''.format(directory))
                shutil.rmtree(directory)

setup(
    cmdclass={
        'clean': CleanCmd,
    },
    install_requires=get_requirements(),
    entry_points={
        'gui_scripts': [
            'auger = auger.__main__:main',
        ],
    },
    data_files=INSTALL_DATA_FILES
)
